version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
    networks:
      - myriad_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:7474 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  graphdb_manager_ai:
    build:
      context: .
      dockerfile: ./agents/graphdb_manager_ai/Dockerfile
    container_name: graphdb_manager_ai
    ports:
      - '5008:5008'
    networks:
      - myriad_network
    environment:
      - FLASK_ENV=development
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      neo4j:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5008/health').raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  lightbulb_definition_ai:
    build:
      context: .
      dockerfile: ./agents/lightbulb_definition_ai/Dockerfile
    ports:
      - '5001:5001'
    container_name: lightbulb_definition_ai
    networks:
      - myriad_network
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

  lightbulb_function_ai:
    build:
      context: .
      dockerfile: ./agents/lightbulb_function_ai/Dockerfile
    ports:
      - '5002:5002'
    container_name: lightbulb_function_ai
    networks:
      - myriad_network
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

  input_processor:
    build:
      context: .
      dockerfile: ./processing/input_processor/Dockerfile
    ports:
      - '5003:5003'
    container_name: input_processor
    networks:
      - myriad_network
    environment:
      - FLASK_ENV=development
      - FLASK_APP=processing.input_processor.app
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5003/health').raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  output_processor:
    build:
      context: .
      dockerfile: ./processing/output_processor/Dockerfile
    ports:
      - '5004:5004'
    container_name: output_processor
    networks:
      - myriad_network
    environment:
      - FLASK_ENV=development
      - FLASK_APP=processing.output_processor.app
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5004/health').raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  lifecycle_manager:
    build:
      context: .
      dockerfile: ./orchestration/lifecycle_manager/Dockerfile
    ports:
      - '5005:5005'
    container_name: lifecycle_manager
    networks:
      - myriad_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./agents:/app/agents
    environment:
      - FLASK_ENV=development
      - FLASK_APP=orchestration.lifecycle_manager.app
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5005/health').raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  agent_registry_service:
    build:
      context: .
      dockerfile: ./orchestration/agent_registry_service/Dockerfile
    ports:
      - '5006:5006'
    container_name: agent_registry_service
    networks:
      - myriad_network
    environment:
      - FLASK_ENV=development
      - FLASK_APP=orchestration.agent_registry_service.app
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5006/health').raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  neo4j_data:

networks:
  myriad_network:
    driver: bridge