version: '3.8'

services:
  lightbulb_definition_ai:
    build:
      context: .
      dockerfile: ./agents/lightbulb_definition_ai/Dockerfile
    ports:
      - '5001:5001'
    container_name: lightbulb_definition_ai
    networks:
      - myriad_network
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

  lightbulb_function_ai:
    build:
      context: .
      dockerfile: ./agents/lightbulb_function_ai/Dockerfile
    ports:
      - '5002:5002'
    container_name: lightbulb_function_ai
    networks:
      - myriad_network
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

  input_processor:
    build:
      context: .
      dockerfile: ./processing/input_processor/Dockerfile
    ports:
      - '5003:5003'
    container_name: input_processor
    networks:
      - myriad_network
    environment:
      - FLASK_ENV=development
      - FLASK_APP=processing.input_processor.app

  output_processor:
    build:
      context: .
      dockerfile: ./processing/output_processor/Dockerfile
    ports:
      - '5004:5004'
    container_name: output_processor
    networks:
      - myriad_network
    environment:
      - FLASK_ENV=development
      - FLASK_APP=processing.output_processor.app

  lifecycle_manager:
    build:
      context: .
      dockerfile: ./orchestration/lifecycle_manager/Dockerfile
    ports:
      - '5005:5005'
    container_name: lifecycle_manager
    networks:
      - myriad_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./agents:/app/agents
    environment:
      - FLASK_ENV=development
      - FLASK_APP=orchestration.lifecycle_manager.app

networks:
  myriad_network:
    driver: bridge