version: '3.8'

services:
  lightbulb_definition_ai:
    build: ./agents/lightbulb_definition_ai
    ports:
      - "5001:5001"
    container_name: lightbulb_definition_ai
    networks:
      - myriad_network
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

  lightbulb_function_ai:
    build: ./agents/lightbulb_function_ai
    ports:
      - "5002:5002"
    container_name: lightbulb_function_ai
    networks:
      - myriad_network
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

networks:
  myriad_network:
    driver: bridge